### ISSUE TITLE
Swoole Missing

### ISSUE THREAD

**Issue by ShaneJMitchell** [leocavalcante/dwoole#2]
I created a new dwoole project, adding only a few additional packages and basing on the leocavalcante/dwoole:1.0-production image, and the container wont start, it just results in an error "Call to undefined function Siler\Swoole\http()".
(Basing my index.php file on what was provided in your production/development example: https://github.com/leocavalcante/dwoole/blob/master/production/example/index.php)

Looking through the Siler package, it doesn't look like that method exists.

Looking deeper at the package, it looks like there is an examples directory inside of the project which contains a swoole example different that what is provided in the official documentation (https://siler.leocavalcante.dev/swoole).  The example in the project actually works, so updating the documentation to reflect a correct and working example would be very helpful.

Also,  Good job in creating a light-weight Swoole compatible framework. 👍

**Comment by leocavalcante** [comment]
Hi @ShaneJMitchell 
Thanks for your feedback. Can you tell me which version of Siler are you using, please?

**Comment by ShaneJMitchell** [comment]
It looks like I was using 1.3 instead of 1.5 which was the issue.
Sorry for the bother.
