### ISSUE TITLE
Connection reset by peer error when testing with ab

### ISSUE THREAD

**Issue by zhanghuanchong** [leocavalcante/dwoole#6]
I wrote a simple script and try to run ab test:

```
ab -n 10000 -c 1000 http://127.0.0.1:9501/ready
```

But got below error "Connection reset by peer":

```
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
apr_socket_recv: Connection reset by peer (54)
```

And also noticed below error in docker's log:
```
NOTICE  swFactoryProcess_finish (ERRNO 1004): send 276 byte failed, because connection[fd=401] is closed
```

When I use less client parameter when calling ab, for instance, 100:
```
ab -n 10000 -c 100 http://127.0.0.1:9501/ready
```

It works. 

I checked the ulimit on both my mac and `docker exec` into the web container, both are `unlimited`:

```
docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                               NAMES
c5e3fa159558        leocavalcante/dwoole:1.0-development   "sh /usr/local/bin/d…"   29 minutes ago      Up 8 minutes        0.0.0.0:9501->9501/tcp              zhanghc_web_1
5cd6752ce12f        mysql                                  "docker-entrypoint.s…"   About an hour ago   Up 8 minutes        33060/tcp, 0.0.0.0:3336->3306/tcp   zhanghc_db_1
686833954e14        memcached                              "docker-entrypoint.s…"   About an hour ago   Up 8 minutes        11211/tcp                           zhanghc_cache_1
```

```
docker exec -it c5e3fa159558 bash
root@c5e3fa159558:/app# ulimit
unlimited
```

Could you please help?

**Comment by leocavalcante** [comment]
I was able to run [Dwoole Development example](https://github.com/leocavalcante/dwoole/tree/master/development/example) over `-n 1000 -c 1000` pretty fast:
![image](https://user-images.githubusercontent.com/183722/64670481-a5b87900-d43b-11e9-8a43-ad85b1e0c946.png)
Can you share more details about your environment and what your code does at `/ready`?
Also, can you test it using the production tag?

**Comment by zhanghuanchong** [comment]
@leocavalcante 
Thanks for the response. I just follow the instruction in https://siler.leocavalcante.dev/swoole to return empty JSON in `/ready`.

I will check the difference between what I did and your development example, and try with production tag later.

I will come back to you once found more clue. Thanks.

**Comment by zhanghuanchong** [comment]
@leocavalcante 
I tried with the dwoole example but got the same error:
![image](https://user-images.githubusercontent.com/3062319/64689918-d7742300-d4c1-11e9-987f-db5c592dff89.png)

If it works for you, it must be some configuration on my Mac. I will check more.

**Comment by zhanghuanchong** [comment]
I cannot find the cause. It seems because of the `ab` installed on my Mac.

I finally resolve it by running the test in a docker `httpd` container which contains official `ab`.
