### ISSUE TITLE
Feature: Dwoole in Alpine 

### ISSUE THREAD

**Issue by leyume** [leocavalcante/dwoole#8]
Hello @leocavalcante 

This really isn't an issue just a feature request and I will be overjoyed if you could help out
The Image size of Dwoole  - 669MB really large...

Please 🙏, can you help with an alpine version that works with Siler 🚀 

Thank you greatly

**Comment by leocavalcante** [comment]
There we go. Please note that tag names was changed to:
- `leocavalcante/dwoole:base`
- `leocavalcante/dwoole:dev`
- `leocavalcante/dwoole:prod`

Its using `--no-cache` and I joined the `RUN` commands. Also the builds was using the experimental `--squash` flag. If you have any other tips to reduce image sizes, please tell me.

**Comment by leyume** [comment]
Thank you for responding fast and all...

So I have been working on it for a couple of hours now trying to optimize and search online

And thankfully have been able to get the image size down from 490MB to 28MB 🚀 
I believe this might help in creating an enhanced solution...

Made a couple of Changes to
- Dockerfile
- docker-entrypoint.sh
- watch.php

Dockerfile

```
FROM alpine:edge

RUN apk add --no-cache \
    php7 \
    php7-common \
    php7-mbstring \
    php7-iconv \
    php7-curl \
    php7-bz2 \
    php7-json \
    php7-ctype \
    php7-mysqli \
    php7-mysqlnd \
    php7-openssl \
    php7-sockets \
    php7-opcache \
    php7-pcntl \
    php7-pdo \
    php7-pdo_mysql \
    php7-phar \
    bash \
    curl \
    php7-pecl-swoole --repository https://mirrors.aliyun.com/alpine/edge/testing/ 
    # php7-pecl-swoole --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

COPY --from=composer /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1


WORKDIR /app

ADD docker-entrypoint.sh watch.php /usr/bin/
ENTRYPOINT [ "sh", "/usr/bin/docker-entrypoint.sh" ]

```

**For docker-entrypoint.sh** - changes to _php /usr/bin/watch.php_ removed **_local_**

```
#!/bin/sh
set -e

composer install

echo "Night gathers, and now my watch begins."
php /usr/bin/watch.php

```


**For watch.php** - changes to _'PHP_BIN'  => '/usr/bin/php'_ removed **_local_**

```
....
$env_vars = [
    'PHP_BIN' => '/usr/bin/php',
    'WATCH_DIR' => '/app',
    'ENTRY_POINT_FILE' => '/app/index.php',
    'WATCH_LIST' => 'php,phtml,twig,env'
];

....

```


What do you think?

**Comment by leocavalcante** [comment]
Ah thank you, very interesting. I'll be looking for it, to understand what is going on.
I see that you are adding PHP to the Alpine image, instead of using PHP oficial image with Alpine tag, maybe that does a lot of the trick. 
I will also have to check this repo that contains the Swoole since Dwoole will depend on that instead of compiling by itself.

And you dont need this:
```Dockerfile
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
```
If you have this:
```Dockerfile
COPY --from=composer /usr/bin/composer /usr/bin/composer
```
Then you can skip curl as well (also, I don't think that bash is needed).

Thank you very much for those infos, I'll check them out.

**Comment by leyume** [comment]
😄 
Yea, just developing my Dockerfile skills
I am glad it helps... can't wait for your final output.
Cheers 👍
